Uncommented pipeline 3

diff --git a/.github/workflows/pipeline_3.yml b/.github/workflows/pipeline_3.yml
--- a/.github/workflows/pipeline_3.yml
+++ b/.github/workflows/pipeline_3.yml
@@ -1,28 +1,29 @@
-#name: Pipeline 3
-#
-#on:
+name: Pipeline 3
+
+on:
+  workflow_dispatch:
 #  workflow_run:
 #    workflows: ["Pipeline 2"]
 #    types:
 #      - completed
-#
-#env:
-#  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#jobs:
-#  check_result:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v4
-#
-#      - name: Check result of Pipeline 2
-#        run: |
-#          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
-#            echo "Pipeline 2 failed."
-#            exit 1
-#          fi
-#
-#      - name: Trigger Pipeline 1 if successful
-#        run: |
-#          echo "Triggering Pipeline 1..."
-#          gh workflow run 'Pipeline 1'
+
+env:
+  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+jobs:
+  check_result:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check result of Pipeline 2
+        run: |
+          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
+            echo "Pipeline 2 failed."
+            exit 1
+          fi
+
+      - name: Trigger Pipeline 1 if successful
+        run: |
+          echo "Triggering Pipeline 1..."
+          gh workflow run 'Pipeline 1'
